services:
  app:
    build: .
    container_name: local-rag-app
    ports:
      - "7860:7860"
    volumes:
      - rag_docs:/app/storage/docs
      - rag_db:/app/storage/db
    depends_on:
      - ollama
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434

  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    command: ["serve"]
    restart: unless-stopped

volumes:
  rag_docs:
  rag_db:
  ollama_data: